version: '3.5'

networks:
  app-rgbmaker:
    driver: bridge

services:
  web:
      image: rgbmakerweb:latest
      build:
        context: .
        dockerfile: ./Dockerfile
      depends_on:
        - "rabbit"
      ports:
        - 5000:5000
      networks:
        - app-rgbmaker

  worker:
      depends_on:
        - "rabbit"
      networks:
        - app-rgbmaker
      command: celery -A app.celery worker -l INFO --concurrency 2 --without-gossip --without-mingle --without-heartbeat

  rabbit:
      image: rabbitmq:latest
      ports: 
        - 5672:5672
      networks:
        - app-rgbmaker
